apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    tier: backend
    app: votingapp
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
