apiVersion: v1
kind: Service
metadata:
  name: resultapp-service
  labels:
    name: resultapp-service
    app: votingapp
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
  selector:
    name: resultapp
    tier: frontend
    app: votingapp