apiVersion: v1
kind: Service
metadata:
  name: votingapp-service
  labels:
    name: votingapp-service
    app: votingapp
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
  selector:
    name: votingapp
    tier: frontend
    app: votingapp