apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    name: worker-deployment
spec:
  template:
    metadata:
      name: worker
      labels:
        name: worker
        tier: frontend
        app: votingapp
    spec:
      containers:
      - name: worker
        image: dockersamples/examplevotingapp_worker
  replicas: 1
  selector:
    matchLabels:
      name: worker
      tier: frontend
      app: votingapp