apiVersion: v1
kind: Pod
metadata:
  name: worker
  labels:
    name: worker
    tier: frontend
    app: votingapp
spec:
  containers:
  - name: worker
    image: dockersamples/examplevotingapp_worker